#  Simple Linear Regression 

## importing the packages

In [21]:
import numpy as np #numerical operation
import pandas as pd #data operation
import matplotlib.pyplot as plt #for graph operation
from matplotlib import rcParams #for graph operation
from sklearn.metrics import accuracy_score,r2_score #to find the accaracy
from sklearn.linear_model import LinearRegression #Linear regression model
from sklearn.model_selection import train_test_split,GridSearchCV #data and best parameter selection

## reading the csv file

In [3]:
data=pd.read_csv('hp_data.csv')

## Displaying the data file 

In [4]:
data.head()

Unnamed: 0     price       place                 built  sqft    sale  \
0        1341   6300000  BTM Layout  Super built-up  Area  1450  Resale   
1        2126  11500000   Yelahanka  Super built-up  Area  2190  Resale   
2         816   3800000  Whitefield  Super built-up  Area  1019  Resale   
3        2708  10500000  Ambalipura  Super built-up  Area  1857  Resale   
4        1041  11500000   Yelahanka  Super built-up  Area  2190  Resale   

   yearsOld  floor  totalFloor  bhk  
0         5      1           4    1  
1         5      3           5    3  
2         1      2           5    2  
3        15      4           5    4  
4         5      3           5    3

## dividing the  data into 2 part(predictor and targeter)

In [6]:
x=data.loc[:,['sqft','yearsOld','floor','totalFloor','bhk']]
y=data.price

## dividing the predictor and targeter into training and testing data 

In [7]:
x_test,x_train,y_test,y_train = train_test_split(x,y,test_size=0.30)

## adding the parameters to gridsearch

In [11]:
parameters = {'n_jobs':[1,10,100,1000]}  

## using the grid search ,finding the best fit parameter 

In [12]:
model=GridSearchCV(LinearRegression(),parameters)

## Fitting the model

In [13]:
model.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_jobs': [1, 10, 100, 1000]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring=None, verbose=0)

## printing the best estimators

In [14]:
model.best_estimator_

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

## printing the best parameters

In [16]:
model.best_params_

{'n_jobs': 1}

## finding the predicted values

In [17]:
y_predict=model.predict(x_test)

In [18]:
y_predict

array([ 8690700.88304174, 12988271.28583482,  7468198.28958431, ...,
        7885883.38570716,  1387611.83760101, 12988271.28583482])

## finding the accuarcy 

In [19]:
r2_score(y_test,y_predict)

0.8208127108068957

## exporting the model 

In [15]:
from sklearn.externals import joblib

In [17]:
joblib.dump(model,'HP.ml')

['HP.ml']

## importing the saved ml model

In [18]:
from sklearn.externals import joblib
model = joblib.load('HP.ml')

In [19]:
model.predict([[1000,2,2,2,2]])

array([-2026249.1464884])

In [20]:
model.predict([[1000,2,2,2,2],[1000,2,2,2,2]])

array([-2026249.1464884, -2026249.1464884])